trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
name: $(Year:yy).$(DayOfYear).$(Rev:rr)
steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: replacetokens@3
  inputs:
    targetFiles: '**/appsettings.json'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '-c $(build-configuration) -o $(Build.ArtifactStagingDirectory) -r $(windows-os) /p:EnvironmentName=$(env-name)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'